import enum


class ErrorCodeEnum(enum.Enum):
    UNDEFINED = "UNDEFINED"
    SUCCESSFULLY_OPERATION = "SUCCESSFULLY_OPERATION"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    TOO_MANY_FAILED_ATTEMPS = "TOO_MANY_FAILED_ATTEMPS"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    UNAUTHORIZED = "UNAUTHORIZED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
